// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cis174projects.Models;

namespace cis174projects.Migrations.Country
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cis174projects.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SportName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameID");

                    b.HasIndex("SportID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "ca",
                            GameID = "Winter",
                            LogoImage = "ca.png",
                            Name = "Canada",
                            SportID = "Curling"
                        },
                        new
                        {
                            CountryID = "se",
                            GameID = "Winter",
                            LogoImage = "se.png",
                            Name = "Sweden",
                            SportID = "Curling"
                        },
                        new
                        {
                            CountryID = "gb",
                            GameID = "Winter",
                            LogoImage = "gb.png",
                            Name = "Great Britain",
                            SportID = "Curling"
                        },
                        new
                        {
                            CountryID = "jm",
                            GameID = "Winter",
                            LogoImage = "jm.png",
                            Name = "Jamaica",
                            SportID = "Bobsleigh"
                        },
                        new
                        {
                            CountryID = "it",
                            GameID = "Winter",
                            LogoImage = "it.png",
                            Name = "Italy",
                            SportID = "Bobsleigh"
                        },
                        new
                        {
                            CountryID = "jp",
                            GameID = "Winter",
                            LogoImage = "jp.png",
                            Name = "Japan",
                            SportID = "Bobsleigh"
                        },
                        new
                        {
                            CountryID = "de",
                            GameID = "Summer",
                            LogoImage = "de.png",
                            Name = "Germany",
                            SportID = "Diving"
                        },
                        new
                        {
                            CountryID = "cn",
                            GameID = "Summer",
                            LogoImage = "cn.png",
                            Name = "China",
                            SportID = "Diving"
                        },
                        new
                        {
                            CountryID = "mx",
                            GameID = "Summer",
                            LogoImage = "mx.png",
                            Name = "Mexico",
                            SportID = "Diving"
                        },
                        new
                        {
                            CountryID = "br",
                            GameID = "Summer",
                            LogoImage = "br.png",
                            Name = "Brazil",
                            SportID = "Road Cycling"
                        },
                        new
                        {
                            CountryID = "nl",
                            GameID = "Summer",
                            LogoImage = "nl.png",
                            Name = "Netherlands",
                            SportID = "Road Cycling"
                        },
                        new
                        {
                            CountryID = "us",
                            GameID = "Summer",
                            LogoImage = "us.png",
                            Name = "USA",
                            SportID = "Road Cycling"
                        },
                        new
                        {
                            CountryID = "th",
                            GameID = "Paralympics",
                            LogoImage = "th.png",
                            Name = "Thailand",
                            SportID = "Archery"
                        },
                        new
                        {
                            CountryID = "uy",
                            GameID = "Paralympics",
                            LogoImage = "uy.png",
                            Name = "Uruguay",
                            SportID = "Archery"
                        },
                        new
                        {
                            CountryID = "ua",
                            GameID = "Paralympics",
                            LogoImage = "ua.png",
                            Name = "Ukraine",
                            SportID = "Archery"
                        },
                        new
                        {
                            CountryID = "at",
                            GameID = "Paralympics",
                            LogoImage = "at.png",
                            Name = "Austria",
                            SportID = "Canoe Sprint"
                        },
                        new
                        {
                            CountryID = "pk",
                            GameID = "Paralympics",
                            LogoImage = "pk.png",
                            Name = "Pakistan",
                            SportID = "Canoe Sprint"
                        },
                        new
                        {
                            CountryID = "zw",
                            GameID = "Paralympics",
                            LogoImage = "zw.png",
                            Name = "Zimbabwe",
                            SportID = "Canoe Sprint"
                        },
                        new
                        {
                            CountryID = "fr",
                            GameID = "Youth",
                            LogoImage = "fr.png",
                            Name = "France",
                            SportID = "Breakdancing"
                        },
                        new
                        {
                            CountryID = "cy",
                            GameID = "Youth",
                            LogoImage = "cy.png",
                            Name = "Cyprus",
                            SportID = "Breakdancing"
                        },
                        new
                        {
                            CountryID = "ru",
                            GameID = "Youth",
                            LogoImage = "ru.png",
                            Name = "Russia",
                            SportID = "Breakdancing"
                        },
                        new
                        {
                            CountryID = "fi",
                            GameID = "Youth",
                            LogoImage = "fi.png",
                            Name = "Finland",
                            SportID = "Skateboarding"
                        },
                        new
                        {
                            CountryID = "sk",
                            GameID = "Youth",
                            LogoImage = "sk.png",
                            Name = "Slovakia",
                            SportID = "Skateboarding"
                        },
                        new
                        {
                            CountryID = "pt",
                            GameID = "Youth",
                            LogoImage = "pt.png",
                            Name = "Portugal",
                            SportID = "Skateboarding"
                        });
                });

            modelBuilder.Entity("cis174projects.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "Winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameID = "Summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameID = "Paralympics",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameID = "Youth",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("cis174projects.Models.Sport", b =>
                {
                    b.Property<string>("SportID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SportName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportID = "Curling",
                            SportName = "Indoor"
                        },
                        new
                        {
                            SportID = "Bobsleigh",
                            SportName = "Outdoor"
                        },
                        new
                        {
                            SportID = "Diving",
                            SportName = "Indoor"
                        },
                        new
                        {
                            SportID = "Road Cycling",
                            SportName = "Outdoor"
                        },
                        new
                        {
                            SportID = "Archery",
                            SportName = "Indoor"
                        },
                        new
                        {
                            SportID = "Canoe Sprint",
                            SportName = "Outdoor"
                        },
                        new
                        {
                            SportID = "Breakdancing",
                            SportName = "Indoor"
                        },
                        new
                        {
                            SportID = "Skateboarding",
                            SportName = "Outdoor"
                        });
                });

            modelBuilder.Entity("cis174projects.Models.Country", b =>
                {
                    b.HasOne("cis174projects.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");

                    b.HasOne("cis174projects.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID");
                });
#pragma warning restore 612, 618
        }
    }
}
